apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-configmap
data:
  KAFKA_BROKERS: "kafka-helm-0.kafka-helm-headless:9092,kafka-helm-1.kafka-helm-headless:9092,kafka-helm-2.kafka-helm-headless:9092"
