apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-deployment
  labels:
    app: price
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price
  template:
    metadata:
      labels:
        app: price
    spec:
      containers:
        - name: price-container
          image: registry.gitlab.com/zoleebossthebosspericulos/kubernetes/price:latest
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: KAFKA_BROKERS
---
apiVersion: v1
kind: Service
metadata:
  name: price-service
spec:
  selector:
    app: price
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
